sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    bucket-name: testlbc1
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET:}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID:}
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
